"""
train_bertimbau.py
==================

Trains and evaluates the stance classifier based on BERTimbau Large
(``neuralmind/bert-large-portuguese-cased``) on YouTube comments annotated
with three classes:

    -1 = against, 0 = neutral, 1 = in favor

Internally label -1 is remapped to 2, so the model classes are
0 (neutral), 1 (in favor) and 2 (against).

Input:
    data/comments.tsv  (generated by hydrate_comments.py)
    Columns: id_comentario, comentario, rotulo [, split]
    If a ``split`` column (train/test) exists, it defines the partition;
    otherwise an 80/20 partition is drawn with ``--seed``.

Outputs (in --output-dir, default: outputs/):
    splits/split_ids.tsv                  train and test IDs used
    models/stance_bertimbau.bin           weights (best training accuracy)
    predictions/test_predictions_and_labels.npz
    metrics/metrics_bert.csv              per-class metrics + accuracy

Usage:
    python train_bertimbau.py
    python train_bertimbau.py --eval-only --checkpoint outputs/models/stance_bertimbau.bin
"""

from __future__ import annotations

import argparse
import random
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import accuracy_score, auc, classification_report, confusion_matrix, roc_curve
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from torch.utils.data import DataLoader, Dataset
from transformers import AdamW, BertConfig, BertModel, BertTokenizer, get_linear_schedule_with_warmup

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "outputs"

PRE_TRAINED_MODEL_NAME = "neuralmind/bert-large-portuguese-cased"
N_CLASSES = 3


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="BERTimbau training and evaluation for stance detection.")
    parser.add_argument("--data", default=str(DATA_DIR / "comments.tsv"),
                        help="Input TSV (default: data/comments.tsv).")
    parser.add_argument("--output-dir", default=str(OUTPUT_DIR),
                        help="Output directory (default: outputs/).")
    parser.add_argument("--model-name", default=PRE_TRAINED_MODEL_NAME)
    parser.add_argument("--max-len", type=int, default=180)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--lr", type=float, default=1e-5)
    parser.add_argument("--test-size", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--eval-only", action="store_true",
                        help="Skip training and evaluate the --checkpoint weights.")
    parser.add_argument("--checkpoint", default=None,
                        help="Weights to load (default: <output-dir>/models/stance_bertimbau.bin).")
    return parser.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


# =========================
# Data
# =========================

def load_data(path: str, seed: int) -> pd.DataFrame:
    data = pd.read_csv(path, sep="\t", dtype={"id_comentario": str})
    data = data.dropna(subset=["rotulo", "comentario"])
    data = data.drop_duplicates(["id_comentario"])
    data = data.sample(frac=1, random_state=seed).reset_index(drop=True)
    data["rotulo"] = data["rotulo"].astype(int)
    data.loc[data["rotulo"] == -1, "rotulo"] = 2
    print("Label distribution (0=neutral, 1=in favor, 2=against):")
    print(data["rotulo"].value_counts().to_string())
    return data


def split_data(data: pd.DataFrame, test_size: float, seed: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    cols = ["id_comentario", "comentario", "rotulo"]
    if "split" in data.columns:
        df_train = data.loc[data["split"] == "train", cols].reset_index(drop=True)
        df_test = data.loc[data["split"] == "test", cols].reset_index(drop=True)
    else:
        df_train, df_test = train_test_split(data[cols], test_size=test_size,
                                             random_state=seed, shuffle=False)
    print(f"Train: {len(df_train)} | Test: {len(df_test)} | Test per class: {Counter(df_test['rotulo'])}")
    return df_train, df_test


class StanceDataset(Dataset):

    def __init__(self, texts, targets, tokenizer, max_len):
        self.texts = texts
        self.targets = targets
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, item):
        text = str(self.texts[item])
        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=self.max_len,
            return_token_type_ids=False,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            return_tensors="pt",
        )
        return {
            "review_text": text,
            "input_ids": encoding["input_ids"].flatten(),
            "attention_mask": encoding["attention_mask"].flatten(),
            "targets": torch.tensor(self.targets[item], dtype=torch.long),
        }


def create_data_loader(df, tokenizer, max_len, batch_size, num_workers):
    ds = StanceDataset(
        texts=df.comentario.to_numpy(),
        targets=df.rotulo.to_numpy(),
        tokenizer=tokenizer,
        max_len=max_len,
    )
    return DataLoader(ds, batch_size=batch_size, num_workers=num_workers)


# =========================
# Model
# =========================

class SentimentClassifier(torch.nn.Module):

    def __init__(self, n_classes, model_name):
        super().__init__()
        config = BertConfig.from_pretrained(model_name)
        config.num_labels = n_classes
        config.return_dict = False
        self.bert = BertModel.from_pretrained(model_name, config=config)
        self.drop = torch.nn.Dropout(p=0.3)
        self.out = torch.nn.Linear(self.bert.config.hidden_size, n_classes)

    def forward(self, input_ids, attention_mask):
        _, pooled_output = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        return self.out(self.drop(pooled_output))


def train_epoch(model, data_loader, loss_fn, optimizer, device, scheduler, n_examples):
    model = model.train()
    losses = []
    correct_predictions = 0

    for d in data_loader:
        input_ids = d["input_ids"].to(device)
        attention_mask = d["attention_mask"].to(device)
        targets = d["targets"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        _, preds = torch.max(outputs, dim=1)
        loss = loss_fn(outputs, targets)

        correct_predictions += torch.sum(preds == targets)
        losses.append(loss.item())

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        scheduler.step()
        optimizer.zero_grad()

    return correct_predictions.double() / n_examples, np.mean(losses)


def get_predictions(model, data_loader, device):
    model = model.eval()
    predictions, prediction_probs, real_values = [], [], []
    with torch.no_grad():
        for d in data_loader:
            input_ids = d["input_ids"].to(device)
            attention_mask = d["attention_mask"].to(device)
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            _, preds = torch.max(outputs, dim=1)
            predictions.extend(preds)
            prediction_probs.extend(outputs)
            real_values.extend(d["targets"])
    return (torch.stack(predictions).cpu().numpy(),
            torch.stack(prediction_probs).cpu().numpy(),
            torch.stack(real_values).cpu().numpy())


# =========================
# Metrics
# =========================

# Original label -> class index in the model.
CLASS_INDEX = {-1: 2, 0: 0, 1: 1}
METRIC_COLUMNS = ["model"] + [
    f"{m}({c})"
    for c in (-1, 1, 0)
    for m in ("precision", "recall", "f1-score", "support", "auc-roc", "TP", "FN", "FP", "TN")
] + ["accuracy"]


def auc_roc_per_class(y_score, y_test):
    y_test_bin = label_binarize(y_test, classes=[0, 1, 2])
    result = []
    for i in range(y_test_bin.shape[1]):
        fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_score[:, i])
        result.append(auc(fpr, tpr))
    return result


def one_vs_rest_counts(matrix, idx):
    tp = matrix[idx, idx]
    fn = matrix[idx].sum() - tp
    fp = matrix[:, idx].sum() - tp
    tn = matrix.sum() - tp - fn - fp
    return [tp, fn, fp, tn]


def compute_metrics(y_test, y_pred, y_score, model_name):
    report = pd.DataFrame(classification_report(y_test, y_pred, output_dict=True)).transpose()
    auc_roc = auc_roc_per_class(y_score, y_test)
    matrix = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])

    row = [model_name]
    for original in (-1, 1, 0):
        idx = CLASS_INDEX[original]
        row += list(report.loc[str(idx)].values)
        row.append(auc_roc[idx])
        row += one_vs_rest_counts(matrix, idx)
    row.append(accuracy_score(y_test, y_pred))
    return pd.DataFrame([row], columns=METRIC_COLUMNS)


# =========================
# Orchestration
# =========================

def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    out = Path(args.output_dir)
    for sub in ("splits", "models", "predictions", "metrics"):
        (out / sub).mkdir(parents=True, exist_ok=True)
    checkpoint = Path(args.checkpoint) if args.checkpoint else out / "models" / "stance_bertimbau.bin"

    data = load_data(args.data, args.seed)
    df_train, df_test = split_data(data, args.test_size, args.seed)
    pd.concat([
        df_train[["id_comentario"]].assign(split="train"),
        df_test[["id_comentario"]].assign(split="test"),
    ]).to_csv(out / "splits" / "split_ids.tsv", sep="\t", index=False)

    tokenizer = BertTokenizer.from_pretrained(args.model_name)
    train_data_loader = create_data_loader(df_train, tokenizer, args.max_len, args.batch_size, args.num_workers)
    test_data_loader = create_data_loader(df_test, tokenizer, args.max_len, args.batch_size, args.num_workers)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    model = SentimentClassifier(N_CLASSES, args.model_name).to(device)

    if args.eval_only:
        model.load_state_dict(torch.load(checkpoint, map_location=device))
    else:
        optimizer = AdamW(model.parameters(), lr=args.lr, correct_bias=False)
        total_steps = len(train_data_loader) * args.epochs
        scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0,
                                                    num_training_steps=total_steps)
        loss_fn = torch.nn.CrossEntropyLoss().to(device)

        best_accuracy = 0
        for epoch in range(args.epochs):
            print(f"Epoch {epoch + 1}/{args.epochs}")
            print("-" * 10)
            train_acc, train_loss = train_epoch(model, train_data_loader, loss_fn, optimizer,
                                                device, scheduler, len(df_train))
            print(f"Train loss {train_loss} accuracy {train_acc}")
            if train_acc > best_accuracy:
                torch.save(model.state_dict(), checkpoint)
                best_accuracy = train_acc

    y_pred, y_score, y_test = get_predictions(model, test_data_loader, device)
    print(classification_report(y_test, y_pred))

    np.savez(out / "predictions" / "test_predictions_and_labels.npz", predictions=y_pred, labels=y_test)
    metrics = compute_metrics(y_test, y_pred, y_score, "BERTimbau")
    metrics.to_csv(out / "metrics" / "metrics_bert.csv")
    print(f"[OK] Results saved to {out}")


if __name__ == "__main__":
    main()
